stages:
  - build

before_script:
  - docker info

build_image:
  stage: build
  script:
    - cd helloworld
    - docker build -t $IMAGE_URI:$IMAGE_TAG .
    - docker push $IMAGE_URI:$IMAGE_TAG
  variables:
    IMAGE_URI: registry.gitlab.com/pacmac/dockerfiles/helloworld
    IMAGE_TAG: latest
