stages:
  - build

variables:
  IMAGE_BASE_URI: myk3s.tencentcloudcr.com/ddxyz/

before_script:
  - docker info
  - docker login -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD} ${DOCKER_REGISTRY_URL}

build_helloworld:
  stage: build

  script:
    - cd helloworld
    - docker build -t $IMAGE_BASE_URI/helloworld:${CI_COMMIT_SHA:0:8}-${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME} .
    - docker push $IMAGE_BASE_URI/helloworld:${CI_COMMIT_SHA:0:8}-${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}
  tags:
    - shell

