stages:
  - build

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  stage: build
  script:
    - cd helloworld
    - docker build -t $IMAGE_URI:$IMAGE_TAG .
    - docker push $IMAGE_URI:$IMAGE_TAG
  variables:
    IMAGE_URI: $CI_REGISTRY_IMAGE
    IMAGE_TAG: latest
  tags:
    - aws11