name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gccpacman/oracle-java-8-cn-docker-image/hello-world
        username: ${{ secrets.GPR_USERNAME }}
        password: ${{ secrets.GPR_TOKEN }}
        registry: docker.pkg.github.com